Repository ngvt1n/Group-Sprint-1-Bookazon, pull requests merged in 2025-09, with the labels that each got.

#12 Refactor: add-Book-interface
  src/Book.java
  src/Bookazon.java
  src/PhysicalBook.java
Labels: refactoring

#17 Add AddressValidator and integrate validation into main
  src/AddressValidator.java
  src/Bookazon.java
Labels: enhancement

#14 Refactor: Pricing & Subscription via interfaces (+ cart/order fixes)
  src/Bookazon.java
  src/CartItem.java
  src/Discounts.java
  src/GoldSubscription.java
  src/NamedSubscription.java
  src/NormalSubscription.java
  src/Order.java
  src/PlatinumSubscription.java
  src/PricingPolicy.java
  src/Printer.java
  src/SilverSubscription.java
  src/Subscription.java
  src/TablePricingPolicy.java
  src/User.java
Labels: bug, enhancement, refactoring
